import tkinter as tk
from PIL import ImageTk, Image, ImageFont, ImageDraw
from tkinter.scrolledtext import ScrolledText
import shutil
import webbrowser
import os.path
from collections import defaultdict  # pour images multiples

def crop_image(image, max_width, max_height):
    width, height = image.size
    if width > max_width or height > max_height:
        left = 0
        top = 0
        right = min(width, max_width)
        bottom = min(height, max_height)
        image = image.crop((left, top, right, bottom))
    return image

def multiply_coordinates(image_dict, factor):
    multiplied_image_dict = {}
    for image_path, positions in image_dict.items():
        multiplied_positions = [(coord[0] * factor, coord[1] * factor) for coord in positions]
        multiplied_image_dict[image_path] = multiplied_positions
    return multiplied_image_dict

def merge_images(image_dict, terrain_image, max_width, max_height, output_path):
    terrain = Image.open(terrain_image)

    for image_path, positions in image_dict.items():
        if os.path.isfile(image_path):
            for position in positions:
                image = Image.open(image_path)
                cropped_image = crop_image(image, max_width, max_height)
                terrain.paste(cropped_image, position)
        else:
            print(f"L'image {image_path} n'existe pas.")

    # Sauvegarder l'image fusionnée en remplaçant l'image "terrain.png"
    terrain.save(output_path)
    TextConsole.insert(tk.INSERT, "terrain.png converted at          output/terrain.png\n")
    TextConsole.insert(tk.INSERT, "----------------------------------\n")
    TextConsole.see(tk.END)

def resize_image(input_path, output_path, new_width, new_height):
    if os.path.isfile(input_path):
        image = Image.open(input_path)
        resized_image = image.resize((new_width, new_height), Image.LANCZOS)
        resized_image.save(output_path)
    else:
        print(f"L'image {input_path} n'existe pas.")

def process_images():
    multiplier_str = x_multiplier.get()

    if multiplier_str == "x16":
        multiplier = 1
        terrain_image_path = "assets/texture/terrain.png"
    elif multiplier_str == "x32":
        multiplier = 2
        terrain_image_path = "assets/texture/terrain32.png"
    else:
        return
    # Dictionnaire des images avec leurs positions
    image_dict = defaultdict(list)

    image_dict["input/blocks/acacia_door_bottom.png"].append((0, 384))
    image_dict["input/blocks/acacia_door_top.png"].append((0, 368))
    image_dict["input/blocks/acacia_leaves.png"].append((176, 320))
    image_dict["input/blocks/acacia_log.png"].append((128, 320))
    image_dict["input/blocks/acacia_log_top.png"].append((144, 320))
    image_dict["input/blocks/acacia_planks.png"].append((160, 320))
    image_dict["input/blocks/acacia_sapling.png"].append((96, 352))
    image_dict["input/blocks/acacia_trapdoor.png"].append((192, 528))
    image_dict["input/blocks/activator_rail.png"].append((208, 176))
    image_dict["input/blocks/activator_rail_on.png"].append((224, 176))
    image_dict["input/blocks/allium.png"].append((0, 352))
    image_dict["input/blocks/andesite.png"].append((48, 256))
    image_dict["input/blocks/anvil.png"].append((112, 208))
    image_dict["input/blocks/anvil_base.png"].append((112, 208))
    image_dict["input/blocks/anvil_top.png"].append((112, 224))
    image_dict["input/blocks/anvil_top_damaged_0.png"].append((112, 224))
    image_dict["input/blocks/anvil_top_damaged_1.png"].append((128, 208))
    image_dict["input/blocks/anvil_top_damaged_2.png"].append((128, 224))
    image_dict["input/blocks/attached_melon_stem.png"].append((32, 416))
    image_dict["input/blocks/attached_pumpkin_stem.png"].append((240, 112))
    image_dict["input/blocks/azure_bluet.png"].append((32, 352))
    image_dict["input/blocks/beacon.png"].append((144, 32))
    image_dict["input/items/barrier.png"].append((176, 368))
    image_dict["input/blocks/bedrock.png"].append((16, 16))
    image_dict["input/blocks/beetroots_stage0.png"].append((0, 400))
    image_dict["input/blocks/beetroots_stage1.png"].append((16, 400))
    image_dict["input/blocks/beetroots_stage2.png"].append((32, 400))
    image_dict["input/blocks/beetroots_stage3.png"].append((48, 400))
    image_dict["input/blocks/beetroots_stage_0.png"].append((0, 400))
    image_dict["input/blocks/beetroots_stage_1.png"].append((16, 400))
    image_dict["input/blocks/beetroots_stage_2.png"].append((32, 400))
    image_dict["input/blocks/beetroots_stage_3.png"].append((48, 400))
    image_dict["input/blocks/birch_door_bottom.png"].append((16, 384))
    image_dict["input/blocks/birch_door_top.png"].append((16, 368))
    image_dict["input/blocks/birch_leaves.png"].append((176, 352))
    image_dict["input/blocks/birch_log.png"].append((80, 112))
    image_dict["input/blocks/birch_log_top.png"].append((240, 256))
    image_dict["input/blocks/birch_planks.png"].append((96, 208))
    image_dict["input/blocks/birch_sapling.png"].append((240, 64))
    image_dict["input/blocks/birch_trapdoor.png"].append((208, 528))
    image_dict["input/blocks/black_concrete.png"].append((0, 432))
    image_dict["input/blocks/black_concrete_powder.png"].append((0, 432))
    image_dict["input/blocks/black_glazed_terracotta.png"].append((0, 464))
    image_dict["input/blocks/black_stained_glass.png"].append((0, 288))
    image_dict["input/blocks/black_stained_glass_pane_top.png"].append((0, 304))
    image_dict["input/blocks/black_terracotta.png"].append((0, 272))
    image_dict["input/blocks/black_wool.png"].append((16, 112))
    image_dict["input/blocks/blue_concrete.png"].append((16, 432))
    image_dict["input/blocks/blue_concrete_powder.png"].append((16, 448))
    image_dict["input/blocks/blue_glazed_terracotta.png"].append((16, 464))
    image_dict["input/blocks/blue_ice.png"].append((240, 480))
    image_dict["input/blocks/blue_orchid.png"].append((16, 352))
    image_dict["input/blocks/blue_stained_glass.png"].append((16, 288))
    image_dict["input/blocks/blue_stained_glass_pane_top.png"].append((16, 304))
    image_dict["input/blocks/blue_terracotta.png"].append((16, 272))
    image_dict["input/blocks/blue_wool.png"].append((16, 176))
    image_dict["input/blocks/bone_block_side.png"].append((0, 416))
    image_dict["input/blocks/bone_block_top.png"].append((16, 416))
    image_dict["input/blocks/bookshelf.png"].append((48, 32))
    image_dict["input/blocks/brain_coral.png"].append((176, 480))
    image_dict["input/blocks/brain_coral_block.png"].append((96, 480))
    image_dict["input/blocks/brain_coral_fan.png"].append((176, 496))
    image_dict["input/blocks/brewing_stand.png"].append((208, 144))
    image_dict["input/blocks/brewing_stand_base.png"].append((192, 144))
    image_dict["input/blocks/brick.png"].append((112, 0))
    image_dict["input/blocks/bricks.png"].append((112, 0))
    image_dict["input/blocks/brown_concrete.png"].append((32, 432))
    image_dict["input/blocks/brown_concrete_powder.png"].append((32, 448))
    image_dict["input/blocks/brown_glazed_terracotta.png"].append((32, 464))
    image_dict["input/blocks/brown_mushroom.png"].append((208, 16))
    image_dict["input/blocks/brown_mushroom_block.png"].append((224, 112))
    image_dict["input/blocks/brown_stained_glass.png"].append((32, 288))
    image_dict["input/blocks/brown_stained_glass_pane_top.png"].append((32, 304))
    image_dict["input/blocks/brown_terracotta.png"].append((32, 272))
    image_dict["input/blocks/brown_wool.png"].append((16, 160))
    image_dict["input/blocks/bubble_coral.png"].append((160, 480))
    image_dict["input/blocks/bubble_coral_block.png"].append((80, 480))
    image_dict["input/blocks/bubble_coral_fan.png"].append((160, 496))
    image_dict["input/blocks/cactus_bottom.png"].append((112, 64))
    image_dict["input/blocks/cactus_side.png"].append((96, 64))
    image_dict["input/blocks/cactus_top.png"].append((80, 64))
    image_dict["input/blocks/cake_bottom.png"].append((192, 112))
    image_dict["input/blocks/cake_inner.png"].append((176, 112))
    image_dict["input/blocks/cake_side.png"].append((160, 112))
    image_dict["input/blocks/cake_top.png"].append((144, 112))
    image_dict["input/blocks/carrots_stage0.png"].append((128, 192))
    image_dict["input/blocks/carrots_stage1.png"].append((144, 192))
    image_dict["input/blocks/carrots_stage2.png"].append((160, 192))
    image_dict["input/blocks/carrots_stage3.png"].append((176, 192))
    image_dict["input/blocks/carved_pumpkin.png"].append((112, 112))
    image_dict["input/blocks/cauldron_bottom.png"].append((176, 144))
    image_dict["input/blocks/cauldron_inner.png"].append((176, 128))
    image_dict["input/blocks/cauldron_side.png"].append((160, 144))
    image_dict["input/blocks/cauldron_top.png"].append((160, 128))
    image_dict["input/blocks/chain_command_block_back.png"].append((64, 400))
    image_dict["input/blocks/chain_command_block_conditional.png"].append((80, 400))
    image_dict["input/blocks/chain_command_block_front.png"].append((96, 400))
    image_dict["input/blocks/chain_command_block_side.png"].append((112, 400))
    image_dict["input/blocks/chipped_anvil_top.png"].append((128, 208))
    image_dict["input/blocks/chiseled_quartz_block.png"].append((144, 224))
    image_dict["input/blocks/chiseled_quartz_block_top.png"].append((144, 208))
    image_dict["input/blocks/chiseled_red_sandstone.png"].append((224, 352))
    image_dict["input/blocks/chiseled_sandstone.png"].append((80, 224))
    image_dict["input/blocks/chiseled_stone_bricks.png"].append((80, 208))
    image_dict["input/blocks/chorus_flower.png"].append((80, 368))
    image_dict["input/blocks/chorus_flower_dead.png"].append((96, 368))
    image_dict["input/blocks/chorus_flower_plant.png"].append((112, 368))
    image_dict["input/blocks/chorus_plant.png"].append((112, 368))
    image_dict["input/blocks/clay.png"].append((128, 64))
    image_dict["input/blocks/coal_block.png"].append((0, 256))
    image_dict["input/blocks/coal_ore.png"].append((32, 32))
    image_dict["input/blocks/coarse_dirt.png"].append((128, 352))
    image_dict["input/blocks/cobblestone.png"].append((0, 16))
    image_dict["input/blocks/cobweb.png"].append((176, 0))
    image_dict["input/blocks/cobblestone_mossy.png"].append((64, 32))
    image_dict["input/blocks/cocoa_stage0.png"].append((160, 160))
    image_dict["input/blocks/cocoa_stage1.png"].append((144, 160))
    image_dict["input/blocks/cocoa_stage2.png"].append((128, 160))
    image_dict["input/blocks/cocoa_stage_0.png"].append((160, 160))
    image_dict["input/blocks/cocoa_stage_1.png"].append((144, 160))
    image_dict["input/blocks/cocoa_stage_2.png"].append((128, 160))
    image_dict["input/blocks/command_block_back.png"].append((128, 400))
    image_dict["input/blocks/command_block_conditional.png"].append((144, 400))
    image_dict["input/blocks/command_block_front.png"].append((160, 400))
    image_dict["input/blocks/command_block_side.png"].append((176, 400))
    image_dict["input/blocks/comparator.png"].append((176, 176))
    image_dict["input/blocks/comparator_off.png"].append((176, 176))
    image_dict["input/blocks/comparator_on.png"].append((192, 176))
    image_dict["input/blocks/conduit.png"].append((96, 128))
    image_dict["input/blocks/cracked_stonebricks.png"].append((80, 96))
    image_dict["input/blocks/crafting_table_front.png"].append((192, 48))
    image_dict["input/blocks/crafting_table_side.png"].append((176, 48))
    image_dict["input/blocks/crafting_table_top.png"].append((176, 32))
    image_dict["input/blocks/cut_red_sandstone.png"].append((240, 352))
    image_dict["input/blocks/cut_sandstone.png"].append((96, 224))
    image_dict["input/blocks/cyan_concrete.png"].append((48, 432))
    image_dict["input/blocks/cyan_concrete_powder.png"].append((48, 448))
    image_dict["input/blocks/cyan_glazed_terracotta.png"].append((48, 464))
    image_dict["input/blocks/cyan_stained_glass.png"].append((48, 288))
    image_dict["input/blocks/cyan_stained_glass_pane_top.png"].append((48, 304))
    image_dict["input/blocks/cyan_terracotta.png"].append((48, 272))
    image_dict["input/blocks/cyan_wool.png"].append((16, 208))
    image_dict["input/blocks/damaged_anvil_top.png"].append((128, 224))
    image_dict["input/blocks/dandelion.png"].append((208, 0))
    image_dict["input/blocks/dark_oak_door_bottom.png"].append((32, 384))
    image_dict["input/blocks/dark_oak_door_top.png"].append((32, 368))
    image_dict["input/blocks/dark_oak_log.png"].append((128, 336))
    image_dict["input/blocks/dark_oak_log_top.png"].append((144, 336))
    image_dict["input/blocks/dark_oak_leaves.png"].append((176, 336))
    image_dict["input/blocks/dark_oak_planks.png"].append((160, 336))
    image_dict["input/blocks/dark_oak_sapling.png"].append((112, 352))
    image_dict["input/blocks/dark_oak_trapdoor.png"].append((224, 528))
    image_dict["input/blocks/dark_prismarine.png"].append((208, 336))
    image_dict["input/blocks/daylight_detector_inverted_top.png"].append((224, 368))
    image_dict["input/blocks/daylight_detector_side.png"].append((160, 48))
    image_dict["input/blocks/daylight_detector_top.png"].append((144, 48))
    image_dict["input/blocks/deadbush.png"].append((112, 48))
    image_dict["input/blocks/dead_brain_coral_block.png"].append((96, 496))
    image_dict["input/blocks/dead_brain_coral_fan.png"].append((176, 512))
    image_dict["input/blocks/dead_bubble_coral_block.png"].append((80, 496))
    image_dict["input/blocks/dead_bubble_coral_fan.png"].append((160, 512))
    image_dict["input/blocks/dead_bush.png"].append((112, 48))
    image_dict["input/blocks/dead_fire_coral_block.png"].append((112, 496))
    image_dict["input/blocks/dead_fire_coral_fan.png"].append((192, 512))
    image_dict["input/blocks/dead_horn_coral_block.png"].append((128, 496))
    image_dict["input/blocks/dead_horn_coral_fan.png"].append((208, 512))
    image_dict["input/blocks/dead_tube_coral_block.png"].append((64, 496))
    image_dict["input/blocks/dead_tube_coral_fan.png"].append((144, 512))
    image_dict["input/blocks/destroy_stage_0.png"].append((0, 240))
    image_dict["input/blocks/destroy_stage_1.png"].append((16, 240))
    image_dict["input/blocks/destroy_stage_2.png"].append((32, 240))
    image_dict["input/blocks/destroy_stage_3.png"].append((48, 240))
    image_dict["input/blocks/destroy_stage_4.png"].append((64, 240))
    image_dict["input/blocks/destroy_stage_5.png"].append((80, 240))
    image_dict["input/blocks/destroy_stage_6.png"].append((96, 240))
    image_dict["input/blocks/destroy_stage_7.png"].append((112, 240))
    image_dict["input/blocks/destroy_stage_8.png"].append((128, 240))
    image_dict["input/blocks/destroy_stage_9.png"].append((144, 240))
    image_dict["input/blocks/detector_rail.png"].append((48, 192))
    image_dict["input/blocks/detector_rail_on.png"].append((208, 208))
    image_dict["input/blocks/diamond_block.png"].append((128, 16))
    image_dict["input/blocks/diamond_ore.png"].append((32, 48))
    image_dict["input/blocks/diorite.png"].append((80, 256))
    image_dict["input/blocks/dirt.png"].append((32, 0))
    image_dict["input/blocks/dirt_path_side.png"].append((144, 368))
    image_dict["input/blocks/dirt_path_top.png"].append((160, 368))
    image_dict["input/blocks/dirt_podzol_side.png"].append((144, 352))
    image_dict["input/blocks/dirt_podzol_top.png"].append((160, 352))
    image_dict["input/blocks/dispenser_front.png"].append((224, 32))
    image_dict["input/blocks/dispenser_front_horizontal.png"].append((224, 32))
    image_dict["input/blocks/dispenser_front_vertical.png"].append((128, 32))
    image_dict["input/blocks/door_acacia_lower.png"].append((0, 384))
    image_dict["input/blocks/door_acacia_upper.png"].append((0, 368))
    image_dict["input/blocks/door_birch_lower.png"].append((16, 384))
    image_dict["input/blocks/door_birch_upper.png"].append((16, 368))
    image_dict["input/blocks/door_dark_oak_lower.png"].append((32, 384))
    image_dict["input/blocks/door_dark_oak_upper.png"].append((32, 368))
    image_dict["input/blocks/door_iron_lower.png"].append((32, 96))
    image_dict["input/blocks/door_iron_upper.png"].append((32, 80))
    image_dict["input/blocks/door_jungle_lower.png"].append((48, 384))
    image_dict["input/blocks/door_jungle_upper.png"].append((48, 368))
    image_dict["input/blocks/door_spruce_lower.png"].append((64, 384))
    image_dict["input/blocks/door_spruce_upper.png"].append((64, 368))
    image_dict["input/blocks/door_wood_lower.png"].append((16, 96))
    image_dict["input/blocks/door_wood_upper.png"].append((16, 80))
    image_dict["input/blocks/double_plant_fern_bottom.png"].append((0, 336))
    image_dict["input/blocks/double_plant_fern_top.png"].append((0, 320))
    image_dict["input/blocks/double_plant_grass_bottom.png"].append((16, 336))
    image_dict["input/blocks/double_plant_grass_top.png"].append((16, 320))
    image_dict["input/blocks/double_plant_paeonia_bottom.png"].append((32, 336))
    image_dict["input/blocks/double_plant_paeonia_top.png"].append((32, 320))
    image_dict["input/blocks/double_plant_rose_bottom.png"].append((48, 336))
    image_dict["input/blocks/double_plant_rose_top.png"].append((48, 320))
    image_dict["input/blocks/double_plant_sunflower_back.png"].append((112, 336))
    image_dict["input/blocks/double_plant_sunflower_bottom.png"].append((96, 336))
    image_dict["input/blocks/double_plant_sunflower_front.png"].append((112, 320))
    image_dict["input/blocks/double_plant_sunflower_top.png"].append((96, 320))
    image_dict["input/blocks/double_plant_syringa_bottom.png"].append((64, 336))
    image_dict["input/blocks/double_plant_syringa_top.png"].append((64, 320))
    image_dict["input/blocks/dragon_egg.png"].append((112, 160))
    image_dict["input/blocks/dried_kelp_side.png"].append((16, 496))
    image_dict["input/blocks/dried_kelp_top.png"].append((0, 496))
    image_dict["input/blocks/dropper_front.png"].append((176, 16))
    image_dict["input/blocks/dropper_front_horizontal.png"].append((176, 16))
    image_dict["input/blocks/dropper_front_vertical.png"].append((160, 32))
    image_dict["input/blocks/emerald_block.png"].append((144, 16))
    image_dict["input/blocks/emerald_ore.png"].append((176, 160))
    image_dict["input/blocks/enchanting_table_bottom.png"].append((112, 176))
    image_dict["input/blocks/enchanting_table_side.png"].append((96, 176))
    image_dict["input/blocks/enchanting_table_top.png"].append((96, 160))
    image_dict["input/blocks/end_bricks.png"].append((128, 368))
    image_dict["input/blocks/end_portal_frame_eye.png"].append((224, 160))
    image_dict["input/blocks/end_portal_frame_side.png"].append((240, 144))
    image_dict["input/blocks/end_portal_frame_top.png"].append((224, 144))
    image_dict["input/blocks/end_rod.png"].append((128, 384))
    image_dict["input/blocks/end_stone.png"].append((240, 160))
    image_dict["input/blocks/end_stone_bricks.png"].append((128, 368))
    image_dict["input/blocks/endframe_eye.png"].append((224, 160))
    image_dict["input/blocks/endframe_side.png"].append((240, 144))
    image_dict["input/blocks/endframe_top.png"].append((224, 144))
    image_dict["input/blocks/farmland.png"].append((112, 80))
    image_dict["input/blocks/farmland_dry.png"].append((112, 80))
    image_dict["input/blocks/farmland_moist.png"].append((96, 80))
    image_dict["input/blocks/farmland_wet.png"].append((96, 80))
    image_dict["input/blocks/fern.png"].append((128, 48))
    image_dict["input/blocks/fire_coral.png"].append((192, 480))
    image_dict["input/blocks/fire_coral_block.png"].append((112, 480))
    image_dict["input/blocks/fire_coral_fan.png"].append((192, 496))
    image_dict["input/blocks/flower_allium.png"].append((0, 352))
    image_dict["input/blocks/flower_blue_orchid.png"].append((16, 352))
    image_dict["input/blocks/flower_dandelion.png"].append((208, 0))
    image_dict["input/blocks/flower_houstonia.png"].append((32, 352))
    image_dict["input/blocks/flower_oxeye_daisy.png"].append((48, 352))
    image_dict["input/blocks/flower_pot.png"].append((160, 176))
    image_dict["input/blocks/flower_rose.png"].append((192, 0))
    image_dict["input/blocks/flower_tulip_orange.png"].append((80, 320))
    image_dict["input/blocks/flower_tulip_pink.png"].append((80, 336))
    image_dict["input/blocks/flower_tulip_red.png"].append((64, 352))
    image_dict["input/blocks/flower_tulip_white.png"].append((80, 352))
    image_dict["input/blocks/frosted_ice_0.png"].append((192, 384))
    image_dict["input/blocks/frosted_ice_1.png"].append((208, 384))
    image_dict["input/blocks/frosted_ice_2.png"].append((224, 384))
    image_dict["input/blocks/frosted_ice_3.png"].append((240, 384))
    image_dict["input/blocks/furnace_front.png"].append((192, 32))
    image_dict["input/blocks/furnace_front_off.png"].append((192, 32))
    image_dict["input/blocks/furnace_front_on.png"].append((208, 48))
    image_dict["input/blocks/furnace_side.png"].append((208, 32))
    image_dict["input/blocks/furnace_top.png"].append((224, 48))
    image_dict["input/blocks/glass.png"].append((16, 48))
    image_dict["input/blocks/glass_black.png"].append((0, 288))
    image_dict["input/blocks/glass_blue.png"].append((16, 288))
    image_dict["input/blocks/glass_brown.png"].append((32, 288))
    image_dict["input/blocks/glass_cyan.png"].append((48, 288))
    image_dict["input/blocks/glass_gray.png"].append((64, 288))
    image_dict["input/blocks/glass_green.png"].append((80, 288))
    image_dict["input/blocks/glass_light_blue.png"].append((96, 288))
    image_dict["input/blocks/glass_lime.png"].append((112, 288))
    image_dict["input/blocks/glass_magenta.png"].append((128, 288))
    image_dict["input/blocks/glass_orange.png"].append((144, 288))
    image_dict["input/blocks/glass_pane_top.png"].append((64, 144))
    image_dict["input/blocks/glass_pane_top_black.png"].append((0, 304))
    image_dict["input/blocks/glass_pane_top_blue.png"].append((16, 304))
    image_dict["input/blocks/glass_pane_top_brown.png"].append((32, 304))
    image_dict["input/blocks/glass_pane_top_cyan.png"].append((48, 304))
    image_dict["input/blocks/glass_pane_top_gray.png"].append((64, 304))
    image_dict["input/blocks/glass_pane_top_green.png"].append((80, 304))
    image_dict["input/blocks/glass_pane_top_light_blue.png"].append((96, 304))
    image_dict["input/blocks/glass_pane_top_lime.png"].append((112, 304))
    image_dict["input/blocks/glass_pane_top_magenta.png"].append((128, 304))
    image_dict["input/blocks/glass_pane_top_orange.png"].append((144, 304))
    image_dict["input/blocks/glass_pane_top_pink.png"].append((160, 304))
    image_dict["input/blocks/glass_pane_top_purple.png"].append((176, 304))
    image_dict["input/blocks/glass_pane_top_red.png"].append((192, 304))
    image_dict["input/blocks/glass_pane_top_silver.png"].append((208, 304))
    image_dict["input/blocks/glass_pane_top_white.png"].append((224, 304))
    image_dict["input/blocks/glass_pane_top_yellow.png"].append((240, 304))
    image_dict["input/blocks/glass_pink.png"].append((160, 288))
    image_dict["input/blocks/glass_purple.png"].append((176, 288))
    image_dict["input/blocks/glass_red.png"].append((192, 288))
    image_dict["input/blocks/glass_silver.png"].append((208, 288))
    image_dict["input/blocks/glass_white.png"].append((224, 288))
    image_dict["input/blocks/glass_yellow.png"].append((240, 288))
    image_dict["input/blocks/glowstone.png"].append((144, 96))
    image_dict["input/blocks/gold_block.png"].append((112, 16))
    image_dict["input/blocks/gold_ore.png"].append((0, 32))
    image_dict["input/blocks/granite.png"].append((112, 256))
    image_dict["input/blocks/grass.png"].append((112, 32))
    image_dict["input/blocks/grass_block_side.png"].append((48, 0))
    image_dict["input/blocks/grass_block_side_overlay.png"].append((96, 32))
    image_dict["input/blocks/grass_block_top.png"].append((0, 0))
    image_dict["input/blocks/grass_block_snow.png"].append((64, 64))
    image_dict["input/blocks/grass_blocks_snow.png"].append((64, 64))
    image_dict["input/blocks/grass_blocks_top.png"].append((0, 0))
    image_dict["input/blocks/grass_path_side.png"].append((144, 368))
    image_dict["input/blocks/grass_path_top.png"].append((160, 368))
    image_dict["input/blocks/grass_side.png"].append((48, 0))
    image_dict["input/blocks/grass_side_overlay.png"].append((96, 32))
    image_dict["input/blocks/grass_side_snowed.png"].append((64, 64))
    image_dict["input/blocks/grass_top.png"].append((0, 0))
    image_dict["input/blocks/gravel.png"].append((48, 16))
    image_dict["input/blocks/gray_concrete.png"].append((64, 432))
    image_dict["input/blocks/gray_concrete_powder.png"].append((64, 448))
    image_dict["input/blocks/gray_glazed_terracotta.png"].append((64, 464))
    image_dict["input/blocks/gray_stained_glass.png"].append((64, 288))
    image_dict["input/blocks/gray_stained_glass_pane_top.png"].append((64, 304))
    image_dict["input/blocks/gray_terracotta.png"].append((64, 272))
    image_dict["input/blocks/gray_wool.png"].append((32, 112))
    image_dict["input/blocks/green_concrete.png"].append((80, 432))
    image_dict["input/blocks/green_concrete_powder.png"].append((80, 448))
    image_dict["input/blocks/green_glazed_terracotta.png"].append((80, 464))
    image_dict["input/blocks/green_stained_glass.png"].append((80, 288))
    image_dict["input/blocks/green_stained_glass_pane_top.png"].append((80, 304))
    image_dict["input/blocks/green_terracotta.png"].append((80, 272))
    image_dict["input/blocks/green_wool.png"].append((16, 144))
    image_dict["input/blocks/hardened_clay.png"].append((16, 256))
    image_dict["input/blocks/hardened_clay_stained_black.png"].append((0, 272))
    image_dict["input/blocks/hardened_clay_stained_blue.png"].append((16, 272))
    image_dict["input/blocks/hardened_clay_stained_brown.png"].append((32, 272))
    image_dict["input/blocks/hardened_clay_stained_cyan.png"].append((48, 272))
    image_dict["input/blocks/hardened_clay_stained_gray.png"].append((64, 272))
    image_dict["input/blocks/hardened_clay_stained_green.png"].append((80, 272))
    image_dict["input/blocks/hardened_clay_stained_light_blue.png"].append((96, 272))
    image_dict["input/blocks/hardened_clay_stained_lime.png"].append((112, 272))
    image_dict["input/blocks/hardened_clay_stained_magenta.png"].append((128, 272))
    image_dict["input/blocks/hardened_clay_stained_orange.png"].append((144, 272))
    image_dict["input/blocks/hardened_clay_stained_pink.png"].append((160, 272))
    image_dict["input/blocks/hardened_clay_stained_purple.png"].append((176, 272))
    image_dict["input/blocks/hardened_clay_stained_red.png"].append((192, 272))
    image_dict["input/blocks/hardened_clay_stained_silver.png"].append((208, 272))
    image_dict["input/blocks/hardened_clay_stained_white.png"].append((224, 272))
    image_dict["input/blocks/hardened_clay_stained_yellow.png"].append((240, 272))
    image_dict["input/blocks/hay_block_side.png"].append((160, 240))
    image_dict["input/blocks/hay_block_top.png"].append((208, 240))
    image_dict["input/blocks/hopper_inside.png"].append((192, 224))
    image_dict["input/blocks/hopper_outside.png"].append((192, 208))
    image_dict["input/blocks/hopper_top.png"].append((192, 240))
    image_dict["input/blocks/horn_coral.png"].append((208, 480))
    image_dict["input/blocks/horn_coral_block.png"].append((128, 480))
    image_dict["input/blocks/horn_coral_fan.png"].append((208, 496))
    image_dict["input/blocks/ice.png"].append((48, 64))
    image_dict["input/blocks/ice_packed.png"].append((192, 368))
    image_dict["input/blocks/iron_bars.png"].append((80, 80))
    image_dict["input/blocks/iron_block.png"].append((96, 16))
    image_dict["input/blocks/iron_door_bottom.png"].append((32, 96))
    image_dict["input/blocks/iron_door_top.png"].append((32, 80))
    image_dict["input/blocks/iron_ore.png"].append((16, 32))
    image_dict["input/blocks/iron_trapdoor.png"].append((240, 368))
    image_dict["input/blocks/itemframe.png"].append((144, 176))
    image_dict["input/blocks/item_frame.png"].append((144, 176))
    image_dict["input/blocks/itemframe_background.png"].append((144, 176))
    image_dict["input/blocks/jack_o_lantern.png"].append((128, 112))
    image_dict["input/blocks/jukebox_side.png"].append((160, 64))
    image_dict["input/blocks/jukebox_top.png"].append((176, 64))
    image_dict["input/blocks/jungle_door_bottom.png"].append((48, 384))
    image_dict["input/blocks/jungle_door_top.png"].append((48, 368))
    image_dict["input/blocks/jungle_leaves.png"].append((64, 192))
    image_dict["input/blocks/jungle_log.png"].append((144, 144))
    image_dict["input/blocks/jungle_log_top.png"].append((224, 256))
    image_dict["input/blocks/jungle_planks.png"].append((112, 192))
    image_dict["input/blocks/jungle_sapling.png"].append((224, 16))
    image_dict["input/blocks/jungle_trapdoor.png"].append((240, 528))
    image_dict["input/blocks/kelp.png"].append((64, 512))
    image_dict["input/blocks/kelp.png"].append((80, 512))
    image_dict["input/blocks/kelp.png"].append((96, 512))
    image_dict["input/blocks/kelp.png"].append((112, 512))
    image_dict["input/blocks/kelp_plant.png"].append((0, 512))
    image_dict["input/blocks/kelp_plant.png"].append((16, 512))
    image_dict["input/blocks/kelp_plant.png"].append((32, 512))
    image_dict["input/blocks/kelp_plant.png"].append((48, 512))
    image_dict["input/blocks/ladder.png"].append((48, 80))
    image_dict["input/blocks/lapis_block.png"].append((0, 144))
    image_dict["input/blocks/lapis_ore.png"].append((0, 160))
    image_dict["input/blocks/large_fern_bottom.png"].append((0, 336))
    image_dict["input/blocks/large_fern_top.png"].append((0, 320))
    image_dict["input/blocks/leaves_acacia.png"].append((176, 320))
    image_dict["input/blocks/leaves_big_oak.png"].append((176, 336))
    image_dict["input/blocks/leaves_birch.png"].append((176, 352))
    image_dict["input/blocks/leaves_jungle.png"].append((64, 192))
    image_dict["input/blocks/leaves_oak.png"].append((64, 48))
    image_dict["input/blocks/leaves_spruce.png"].append((64, 128))
    image_dict["input/blocks/lever.png"].append((0, 96))
    image_dict["input/blocks/light_blue_concrete.png"].append((96, 432))
    image_dict["input/blocks/light_blue_concrete_powder.png"].append((96, 448))
    image_dict["input/blocks/light_blue_glazed_terracotta.png"].append((96, 464))
    image_dict["input/blocks/light_blue_stained_glass.png"].append((96, 288))
    image_dict["input/blocks/light_blue_stained_glass_pane_top.png"].append((96, 304))
    image_dict["input/blocks/light_blue_terracotta.png"].append((96, 272))
    image_dict["input/blocks/light_blue_wool.png"].append((32, 176))
    image_dict["input/blocks/light_gray_concrete.png"].append((208, 432))
    image_dict["input/blocks/light_gray_concrete_powder.png"].append((208, 448))
    image_dict["input/blocks/light_gray_glazed_terracotta.png"].append((208, 464))
    image_dict["input/blocks/light_gray_stained_glass.png"].append((208, 288))
    image_dict["input/blocks/light_gray_stained_glass_pane_top.png"].append((208, 304))
    image_dict["input/blocks/light_gray_terracotta.png"].append((208, 272))
    image_dict["input/blocks/light_gray_wool.png"].append((16, 224))
    image_dict["input/blocks/lilac_bottom.png"].append((64, 336))
    image_dict["input/blocks/lilac_top.png"].append((64, 320))
    image_dict["input/blocks/lily_pad.png"].append((208, 96))
    image_dict["input/blocks/lime_concrete.png"].append((112, 432))
    image_dict["input/blocks/lime_concrete_powder.png"].append((112, 448))
    image_dict["input/blocks/lime_glazed_terracotta.png"].append((112, 464))
    image_dict["input/blocks/lime_stained_glass.png"].append((112, 288))
    image_dict["input/blocks/lime_stained_glass_pane_top.png"].append((112, 304))
    image_dict["input/blocks/lime_terracotta.png"].append((112, 272))
    image_dict["input/blocks/lime_wool.png"].append((32, 144))
    image_dict["input/blocks/magenta_concrete.png"].append((128, 432))
    image_dict["input/blocks/magenta_concrete_powder.png"].append((128, 448))
    image_dict["input/blocks/magenta_glazed_terracotta.png"].append((128, 464))
    image_dict["input/blocks/magenta_stained_glass.png"].append((128, 288))
    image_dict["input/blocks/magenta_stained_glass_pane_top.png"].append((128, 304))
    image_dict["input/blocks/magenta_terracotta.png"].append((128, 272))
    image_dict["input/blocks/magenta_wool.png"].append((32, 192))
    image_dict["input/blocks/magma.png"].append((144, 384))
    image_dict["input/blocks/magma_block.png"].append((144, 384))
    image_dict["input/blocks/melon_side.png"].append((128, 128))
    image_dict["input/blocks/melon_stem.png"].append((48, 416))
    image_dict["input/blocks/melon_stem_connected.png"].append((32, 416))
    image_dict["input/blocks/melon_stem_disconnected.png"].append((48, 416))
    image_dict["input/blocks/melon_top.png"].append((144, 128))
    image_dict["input/blocks/mob_spawner.png"].append((16, 64))
    image_dict["input/blocks/mossy_cobblestone.png"].append((64, 32))
    image_dict["input/blocks/mossy_stone_bricks.png"].append((64, 96))
    image_dict["input/blocks/mushroom_block_inside.png"].append((224, 128))
    image_dict["input/blocks/mushroom_block_skin_brown.png"].append((224, 112))
    image_dict["input/blocks/mushroom_block_skin_inside.png"].append((208, 112))
    image_dict["input/blocks/mushroom_block_skin_stem.png"].append((208, 128))
    image_dict["input/blocks/mushroom_brown.png"].append((208, 16))
    image_dict["input/blocks/mushroom_red.png"].append((192, 16))
    image_dict["input/blocks/mushroom_stem.png"].append((208, 128))
    image_dict["input/blocks/mycelium_side.png"].append((208, 64))
    image_dict["input/blocks/mycelium_top.png"].append((224, 64))
    image_dict["input/blocks/netherrack.png"].append((112, 96))
    image_dict["input/blocks/nether_brick.png"].append((0, 224))
    image_dict["input/blocks/nether_bricks.png"].append((0, 224))
    image_dict["input/blocks/nether_quartz_ore.png"].append((240, 176))
    image_dict["input/blocks/nether_wart_block.png"].append((160, 384))
    image_dict["input/blocks/nether_wart_stage0.png"].append((32, 224))
    image_dict["input/blocks/nether_wart_stage1.png"].append((48, 224))
    image_dict["input/blocks/nether_wart_stage2.png"].append((64, 224))
    image_dict["input/blocks/nether_wart_stage_0.png"].append((32, 224))
    image_dict["input/blocks/nether_wart_stage_1.png"].append((48, 224))
    image_dict["input/blocks/nether_wart_stage_2.png"].append((64, 224))
    image_dict["input/blocks/note_block.png"].append((32, 256))
    image_dict["input/blocks/noteblock.png"].append((32, 256))
    image_dict["input/blocks/oak_door_bottom.png"].append((16, 96))
    image_dict["input/blocks/oak_door_top.png"].append((16, 80))
    image_dict["input/blocks/oak_leave.png"].append((64, 48))
    image_dict["input/blocks/oak_leaves.png"].append((64, 48))
    image_dict["input/blocks/oak_log.png"].append((64, 16))
    image_dict["input/blocks/oak_log_top.png"].append((80, 16))
    image_dict["input/blocks/oak_planks.png"].append((64, 0))
    image_dict["input/blocks/oak_sapling.png"].append((240, 0))
    image_dict["input/blocks/oak_trapdoor.png"].append((64, 80))
    image_dict["input/blocks/observer_back.png"].append((96, 416))
    image_dict["input/blocks/observer_back_off.png"].append((112, 416))
    image_dict["input/blocks/observer_back_on.png"].append((112, 416))
    image_dict["input/blocks/observer_front.png"].append((64, 416))
    image_dict["input/blocks/observer_side.png"].append((80, 416))
    image_dict["input/blocks/observer_top.png"].append((128, 416))
    image_dict["input/blocks/obsidian.png"].append((80, 32))
    image_dict["input/blocks/orange_concrete.png"].append((144, 432))
    image_dict["input/blocks/orange_concrete_powder.png"].append((144, 448))
    image_dict["input/blocks/orange_glazed_terracotta.png"].append((144, 464))
    image_dict["input/blocks/orange_stained_glass.png"].append((144, 288))
    image_dict["input/blocks/orange_stained_glass_pane_top.png"].append((144, 304))
    image_dict["input/blocks/orange_terracotta.png"].append((144, 272))
    image_dict["input/blocks/orange_tulip.png"].append((80, 320))
    image_dict["input/blocks/orange_wool.png"].append((32, 208))
    image_dict["input/blocks/oxeye_daisy.png"].append((48, 352))
    image_dict["input/blocks/packed_ice.png"].append((192, 368))
    image_dict["input/blocks/peony_bottom.png"].append((32, 336))
    image_dict["input/blocks/peony_top.png"].append((32, 320))
    image_dict["input/blocks/pink_concrete.png"].append((160, 432))
    image_dict["input/blocks/pink_concrete_powder.png"].append((160, 448))
    image_dict["input/blocks/pink_glazed_terracotta.png"].append((160, 464))
    image_dict["input/blocks/pink_stained_glass.png"].append((160, 288))
    image_dict["input/blocks/pink_stained_glass_pane_top.png"].append((160, 304))
    image_dict["input/blocks/pink_terracotta.png"].append((160, 272))
    image_dict["input/blocks/pink_tulip.png"].append((80, 336))
    image_dict["input/blocks/pink_wool.png"].append((32, 128))
    image_dict["input/blocks/piston_bottom.png"].append((208, 96))
    image_dict["input/blocks/piston_inner.png"].append((224, 96))
    image_dict["input/blocks/piston_side.png"].append((192, 96))
    image_dict["input/blocks/piston_top.png"].append((176, 96))
    image_dict["input/blocks/piston_top_normal.png"].append((176, 96))
    image_dict["input/blocks/piston_top_sticky.png"].append((160, 96))
    image_dict["input/blocks/planks_acacia.png"].append((112, 192))
    image_dict["input/blocks/planks_big_oak.png"].append((160, 336))
    image_dict["input/blocks/planks_birch.png"].append((96, 208))
    image_dict["input/blocks/planks_jungle.png"].append((112, 192))
    image_dict["input/blocks/planks_oak.png"].append((64, 0))
    image_dict["input/blocks/planks_spruce.png"].append((96, 192))
    image_dict["input/blocks/podzol_side.png"].append((144, 352))
    image_dict["input/blocks/podzol_top.png"].append((160, 352))
    image_dict["input/blocks/polished_andesite.png"].append((64, 256))
    image_dict["input/blocks/polished_diorite.png"].append((96, 256))
    image_dict["input/blocks/polished_granite.png"].append((128, 256))
    image_dict["input/blocks/poppy.png"].append((192, 0))
    image_dict["input/blocks/potato_stage0.png"].append((144, 256))
    image_dict["input/blocks/potato_stage1.png"].append((160, 256))
    image_dict["input/blocks/potato_stage2.png"].append((176, 256))
    image_dict["input/blocks/potato_stage3.png"].append((192, 256))
    image_dict["input/blocks/potato_stage_0.png"].append((144, 256))
    image_dict["input/blocks/potato_stage_1.png"].append((160, 256))
    image_dict["input/blocks/potato_stage_2.png"].append((176, 256))
    image_dict["input/blocks/potato_stage_3.png"].append((192, 256))
    image_dict["input/blocks/potatoes_stage0.png"].append((144, 256))
    image_dict["input/blocks/potatoes_stage1.png"].append((160, 256))
    image_dict["input/blocks/potatoes_stage2.png"].append((176, 256))
    image_dict["input/blocks/potatoes_stage3.png"].append((192, 256))
    image_dict["input/blocks/powered_rail.png"].append((48, 160))
    image_dict["input/blocks/powered_rail_on.png"].append((48, 176))
    image_dict["input/blocks/prismarine.png"].append((208, 352))
    image_dict["input/blocks/prismarine_bricks.png"].append((208, 320))
    image_dict["input/blocks/prismarine_dark.png"].append((208, 336))
    image_dict["input/blocks/prismarine_rough.png"].append((208, 352))
    image_dict["input/blocks/pumpkin_face_off.png"].append((112, 112))
    image_dict["input/blocks/pumpkin_face_on.png"].append((128, 112))
    image_dict["input/blocks/pumpkin_side.png"].append((96, 112))
    image_dict["input/blocks/pumpkin_stem.png"].append((240, 96))
    image_dict["input/blocks/pumpkin_stem_connected.png"].append((240, 112))
    image_dict["input/blocks/pumpkin_stem_disconnected.png"].append((240, 96))
    image_dict["input/blocks/pumpkin_top.png"].append((96, 96))
    image_dict["input/blocks/purple_concrete.png"].append((176, 432))
    image_dict["input/blocks/purple_concrete_powder.png"].append((176, 448))
    image_dict["input/blocks/purple_glazed_terracotta.png"].append((176, 464))
    image_dict["input/blocks/purple_stained_glass.png"].append((176, 288))
    image_dict["input/blocks/purple_stained_glass_pane_top.png"].append((176, 304))
    image_dict["input/blocks/purple_terracotta.png"].append((176, 272))
    image_dict["input/blocks/purple_wool.png"].append((16, 192))
    image_dict["input/blocks/purpur_block.png"].append((80, 384))
    image_dict["input/blocks/purpur_pillar.png"].append((96, 384))
    image_dict["input/blocks/purpur_pillar_top.png"].append((112, 384))
    image_dict["input/blocks/quartz_block_bottom.png"].append((176, 240))
    image_dict["input/blocks/quartz_block_chiseled.png"].append((144, 224))
    image_dict["input/blocks/quartz_block_chiseled_top.png"].append((144, 208))
    image_dict["input/blocks/quartz_block_lines.png"].append((160, 224))
    image_dict["input/blocks/quartz_block_lines_top.png"].append((160, 208))
    image_dict["input/blocks/quartz_block_side.png"].append((176, 224))
    image_dict["input/blocks/quartz_block_top.png"].append((176, 208))
    image_dict["input/blocks/quartz_ore.png"].append((240, 176))
    image_dict["input/blocks/quartz_pillar.png"].append((160, 224))
    image_dict["input/blocks/quartz_pillar_top.png"].append((160, 208))
    image_dict["input/blocks/rail.png"].append((0, 128))
    image_dict["input/blocks/rail_corner.png"].append((0, 112))
    image_dict["input/blocks/rail_activator.png"].append((208, 176))
    image_dict["input/blocks/rail_activator_powered.png"].append((224, 176))
    image_dict["input/blocks/rail_detector.png"].append((48, 192))
    image_dict["input/blocks/rail_detector_powered.png"].append((208, 208))
    image_dict["input/blocks/rail_golden.png"].append((48, 160))
    image_dict["input/blocks/rail_golden_powered.png"].append((48, 176))
    image_dict["input/blocks/rail_normal.png"].append((0, 128))
    image_dict["input/blocks/rail_normal_turned.png"].append((0, 112))
    image_dict["input/blocks/red_concrete.png"].append((192, 432))
    image_dict["input/blocks/red_concrete_powder.png"].append((192, 448))
    image_dict["input/blocks/red_glazed_terracotta.png"].append((192, 464))
    image_dict["input/blocks/red_mushroom.png"].append((192, 16))
    image_dict["input/blocks/red_mushroom_block.png"].append((208, 112))
    image_dict["input/blocks/red_sand.png"].append((224, 320))
    image_dict["input/blocks/red_sandstone.png"].append((240, 336))
    image_dict["input/blocks/red_sandstone_bottom.png"].append((224, 336))
    image_dict["input/blocks/red_sandstone_carved.png"].append((224, 352))
    image_dict["input/blocks/red_sandstone_normal.png"].append((240, 336))
    image_dict["input/blocks/red_sandstone_smooth.png"].append((240, 352))
    image_dict["input/blocks/red_sandstone_top.png"].append((240, 320))
    image_dict["input/blocks/red_nether_bricks.png"].append((176, 384))
    image_dict["input/blocks/red_stained_glass.png"].append((192, 288))
    image_dict["input/blocks/red_stained_glass_pane_top.png"].append((192, 304))
    image_dict["input/blocks/red_terracotta.png"].append((192, 272))
    image_dict["input/blocks/red_tulip.png"].append((64, 352))
    image_dict["input/blocks/red_wool.png"].append((16, 128))
    image_dict["input/blocks/redstone_block.png"].append((160, 16))
    image_dict["input/blocks/redstone_lamp.png"].append((48, 208))
    image_dict["input/blocks/redstone_lamp_off.png"].append((48, 208))
    image_dict["input/blocks/redstone_lamp_on.png"].append((64, 208))
    image_dict["input/blocks/redstone_ore.png"].append((48, 48))
    image_dict["input/blocks/redstone_torch.png"].append((48, 96))
    image_dict["input/blocks/redstone_torch_off.png"].append((48, 112))
    image_dict["input/blocks/redstone_torch_on.png"].append((48, 96))
    image_dict["input/blocks/reeds.png"].append((144, 64))
    image_dict["input/blocks/repeater.png"].append((48, 128))
    image_dict["input/blocks/repeater_off.png"].append((48, 128))
    image_dict["input/blocks/repeater_on.png"].append((48, 144))
    image_dict["input/blocks/repeating_command_block_back.png"].append((192, 400))
    image_dict["input/blocks/repeating_command_block_conditional.png"].append((208, 400))
    image_dict["input/blocks/repeating_command_block_front.png"].append((224, 400))
    image_dict["input/blocks/repeating_command_block_side.png"].append((240, 400))
    image_dict["input/blocks/rose_bush_bottom.png"].append((48, 336))
    image_dict["input/blocks/rose_bush_top.png"].append((48, 320))
    image_dict["input/blocks/sand.png"].append((32, 16))
    image_dict["input/blocks/sandstone.png"].append((0, 192))
    image_dict["input/blocks/sandstone_bottom.png"].append((0, 208))
    image_dict["input/blocks/sandstone_carved.png"].append((80, 224))
    image_dict["input/blocks/sandstone_normal.png"].append((0, 192))
    image_dict["input/blocks/sandstone_smooth.png"].append((96, 224))
    image_dict["input/blocks/sandstone_top.png"].append((0, 176))
    image_dict["input/blocks/sapling_acacia.png"].append((96, 352))
    image_dict["input/blocks/sapling_birch.png"].append((240, 64))
    image_dict["input/blocks/sapling_jungle.png"].append((224, 16))
    image_dict["input/blocks/sapling_oak.png"].append((240, 0))
    image_dict["input/blocks/sapling_roofed_oak.png"].append((112, 352))
    image_dict["input/blocks/sapling_spruce.png"].append((240, 48))
    image_dict["input/blocks/sea_lantern.png"].append((208, 368))
    image_dict["input/blocks/sea_pickle.png"].append((224, 480))
    image_dict["input/blocks/seagrass.png"].append((128, 512))
    image_dict["input/blocks/seagrass.png"].append((32, 496))
    image_dict["input/blocks/slime_block.png"].append((192, 192))
    image_dict["input/blocks/smooth_stone_slab_side.png"].append((80, 0))
    image_dict["input/blocks/smooth_stone.png"].append((96, 0))
    image_dict["input/blocks/snow.png"].append((32, 64))
    image_dict["input/blocks/soul_sand.png"].append((128, 96))
    image_dict["input/blocks/spawner.png"].append((16, 64))
    image_dict["input/blocks/sponge.png"].append((0, 48))
    image_dict["input/blocks/sponge_wet.png"].append((192, 128))
    image_dict["input/blocks/spruce_door_bottom.png"].append((64, 384))
    image_dict["input/blocks/spruce_door_top.png"].append((64, 368))
    image_dict["input/blocks/spruce_leaves.png"].append((64, 128))
    image_dict["input/blocks/spruce_log.png"].append((64, 112))
    image_dict["input/blocks/spruce_log_top.png"].append((208, 256))
    image_dict["input/blocks/spruce_planks.png"].append((96, 192))
    image_dict["input/blocks/spruce_sapling.png"].append((240, 48))
    image_dict["input/blocks/spruce_trapdoor.png"].append((240, 512))
    image_dict["input/blocks/stone.png"].append((16, 0))
    image_dict["input/blocks/stone_andesite.png"].append((48, 256))
    image_dict["input/blocks/stone_andesite_smooth.png"].append((64, 256))
    image_dict["input/blocks/stone_brick.png"].append((96, 48))
    image_dict["input/blocks/stone_bricks.png"].append((96, 48))
    image_dict["input/blocks/stone_diorite.png"].append((80, 256))
    image_dict["input/blocks/stone_diorite_smooth.png"].append((96, 256))
    image_dict["input/blocks/stone_granite.png"].append((112, 256))
    image_dict["input/blocks/stone_granite_smooth.png"].append((128, 256))
    image_dict["input/blocks/stone_slab_side.png"].append((80, 0))
    image_dict["input/blocks/stone_slab_top.png"].append((96, 0))
    image_dict["input/blocks/stonebrick.png"].append((96, 48))
    image_dict["input/blocks/stonebrick_carved.png"].append((80, 208))
    image_dict["input/blocks/stonebrick_cracked.png"].append((80, 96))
    image_dict["input/blocks/stonebrick_mossy.png"].append((64, 96))
    image_dict["input/blocks/stripped_acacia_log.png"].append((32, 528))
    image_dict["input/blocks/stripped_acacia_log_top.png"].append((48, 528))
    image_dict["input/blocks/stripped_birch_log.png"].append((64, 528))
    image_dict["input/blocks/stripped_birch_log_top.png"].append((80, 528))
    image_dict["input/blocks/stripped_dark_oak_log.png"].append((96, 528))
    image_dict["input/blocks/stripped_dark_oak_log_top.png"].append((112, 528))
    image_dict["input/blocks/stripped_jungle_log.png"].append((128, 528))
    image_dict["input/blocks/stripped_jungle_log_top.png"].append((144, 528))
    image_dict["input/blocks/stripped_oak_log.png"].append((0, 528))
    image_dict["input/blocks/stripped_oak_log_top.png"].append((16, 528))
    image_dict["input/blocks/stripped_spruce_log.png"].append((160, 528))
    image_dict["input/blocks/stripped_spruce_log_top.png"].append((176, 528))
    image_dict["input/blocks/structure_block.png"].append((176, 416))
    image_dict["input/blocks/structure_block_corner.png"].append((192, 416))
    image_dict["input/blocks/structure_block_data.png"].append((208, 416))
    image_dict["input/blocks/structure_block_load.png"].append((224, 416))
    image_dict["input/blocks/structure_block_save.png"].append((240, 416))
    image_dict["input/blocks/sugar_cane.png"].append((144, 64))
    image_dict["input/blocks/sunflower_back.png"].append((112, 336))
    image_dict["input/blocks/sunflower_bottom.png"].append((96, 336))
    image_dict["input/blocks/sunflower_front.png"].append((112, 320))
    image_dict["input/blocks/sunflower_top.png"].append((96, 320))
    image_dict["input/blocks/tall_grass_bottom.png"].append((16, 336))
    image_dict["input/blocks/tall_grass_top.png"].append((16, 320))
    image_dict["input/blocks/tall_seagrass_bottom.png"].append((48, 496))
    image_dict["input/blocks/tall_seagrass_top.png"].append((48, 480))
    image_dict["input/blocks/tallgrass.png"].append((112, 32))
    image_dict["input/blocks/terracotta.png"].append((16, 256))
    image_dict["input/blocks/tnt_bottom.png"].append((160, 0))
    image_dict["input/blocks/tnt_side.png"].append((128, 0))
    image_dict["input/blocks/tnt_top.png"].append((144, 0))
    image_dict["input/blocks/torch.png"].append((0, 80))
    image_dict["input/blocks/torch_on.png"].append((0, 80))
    image_dict["input/blocks/trapdoor.png"].append((64, 80))
    image_dict["input/blocks/trip_wire.png"].append((208, 160))
    image_dict["input/blocks/trip_wire_source.png"].append((192, 160))
    image_dict["input/blocks/tripwire.png"].append((208, 160))
    image_dict["input/blocks/tripwire_hook.png"].append((192, 160))
    image_dict["input/blocks/tube_coral.png"].append((144, 480))
    image_dict["input/blocks/tube_coral_block.png"].append((64, 480))
    image_dict["input/blocks/tube_coral_fan.png"].append((144, 496))
    image_dict["input/blocks/turtle_egg.png"].append((112, 128))
    image_dict["input/blocks/turtle_egg_slightly_cracked.png"].append((112, 144))
    image_dict["input/blocks/turtle_egg_very_cracked.png"].append((128, 144))
    image_dict["input/blocks/vine.png"].append((240, 128))
    image_dict["input/blocks/waterlily.png"].append((192, 64))
    image_dict["input/blocks/web.png"].append((176, 0))
    image_dict["input/blocks/wet_sponge.png"].append((192, 128))
    image_dict["input/blocks/wheat_stage0.png"].append((128, 80))
    image_dict["input/blocks/wheat_stage1.png"].append((144, 80))
    image_dict["input/blocks/wheat_stage2.png"].append((160, 80))
    image_dict["input/blocks/wheat_stage3.png"].append((176, 80))
    image_dict["input/blocks/wheat_stage4.png"].append((192, 80))
    image_dict["input/blocks/wheat_stage5.png"].append((208, 80))
    image_dict["input/blocks/wheat_stage6.png"].append((224, 80))
    image_dict["input/blocks/wheat_stage7.png"].append((240, 80))
    image_dict["input/blocks/wheat_stage_0.png"].append((128, 80))
    image_dict["input/blocks/wheat_stage_1.png"].append((144, 80))
    image_dict["input/blocks/wheat_stage_2.png"].append((160, 80))
    image_dict["input/blocks/wheat_stage_3.png"].append((176, 80))
    image_dict["input/blocks/wheat_stage_4.png"].append((192, 80))
    image_dict["input/blocks/wheat_stage_5.png"].append((208, 80))
    image_dict["input/blocks/wheat_stage_6.png"].append((224, 80))
    image_dict["input/blocks/wheat_stage_7.png"].append((240, 80))
    image_dict["input/blocks/white_concrete.png"].append((224, 432))
    image_dict["input/blocks/white_concrete_powder.png"].append((224, 448))
    image_dict["input/blocks/white_glazed_terracotta.png"].append((224, 464))
    image_dict["input/blocks/white_stained_glass.png"].append((224, 288))
    image_dict["input/blocks/white_stained_glass_pane_top.png"].append((224, 304))
    image_dict["input/blocks/white_terracotta.png"].append((224, 272))
    image_dict["input/blocks/white_tulip.png"].append((80, 352))
    image_dict["input/blocks/white_wool.png"].append((0, 64))
    image_dict["input/blocks/wool_colored_black.png"].append((16, 112))
    image_dict["input/blocks/wool_colored_blue.png"].append((16, 176))
    image_dict["input/blocks/wool_colored_brown.png"].append((16, 160))
    image_dict["input/blocks/wool_colored_cyan.png"].append((16, 208))
    image_dict["input/blocks/wool_colored_gray.png"].append((32, 112))
    image_dict["input/blocks/wool_colored_green.png"].append((16, 144))
    image_dict["input/blocks/wool_colored_light_blue.png"].append((32, 176))
    image_dict["input/blocks/wool_colored_lime.png"].append((32, 144))
    image_dict["input/blocks/wool_colored_magenta.png"].append((32, 192))
    image_dict["input/blocks/wool_colored_orange.png"].append((32, 208))
    image_dict["input/blocks/wool_colored_pink.png"].append((32, 128))
    image_dict["input/blocks/wool_colored_purple.png"].append((16, 192))
    image_dict["input/blocks/wool_colored_red.png"].append((16, 128))
    image_dict["input/blocks/wool_colored_silver.png"].append((16, 224))
    image_dict["input/blocks/wool_colored_white.png"].append((0, 64))
    image_dict["input/blocks/wool_colored_yellow.png"].append((32, 160))
    image_dict["input/blocks/yellow_concrete.png"].append((240, 432))
    image_dict["input/blocks/yellow_concrete_powder.png"].append((240, 448))
    image_dict["input/blocks/yellow_glazed_terracotta.png"].append((240, 464))
    image_dict["input/blocks/yellow_stained_glass.png"].append((240, 288))
    image_dict["input/blocks/yellow_stained_glass_pane_top.png"].append((240, 304))
    image_dict["input/blocks/yellow_terracotta.png"].append((240, 272))
    image_dict["input/blocks/yellow_wool.png"].append((32, 160))

    # Chemin de l'image de sortie
    terrain_output_path = "output/terrain.png"

    # Copie de l'image de terrain vers le répertoire de sortie
    shutil.copyfile(terrain_image_path, terrain_output_path)

    # Multiplier les coordonnées par le facteur choisi (x16 ou x32)
    image_dict = multiply_coordinates(image_dict, multiplier)

    # Appel de la fonction pour fusionner les images sur terrain.png
    merge_images(image_dict, terrain_output_path, 16 * multiplier, 16 * multiplier, terrain_output_path)


    # Redimensionner terrainMipMapLevel2.png en 128x272 ou 256x544
    resize_image(terrain_output_path, "output/terrainMipMapLevel2.png", 128 * multiplier, 272 * multiplier)
    TextConsole.insert(tk.INSERT, "terrainMipMapLevel2.png converted output/terrainMipMapLevel2.png\n")
    TextConsole.insert(tk.INSERT, "----------------------------------\n")
    TextConsole.see(tk.END)

    # Copier et redimensionner terrainMipMapLevel2.png pour terrainMipMapLevel3.png
    shutil.copyfile("output/terrainMipMapLevel2.png", "output/terrainMipMapLevel3.png")
    resize_image("output/terrainMipMapLevel3.png", "output/terrainMipMapLevel3.png", 64 * multiplier, 136 * multiplier)
    TextConsole.insert(tk.INSERT, "terrainMipMapLevel3.png converted output/terrainMipMapLevel3.png\n")
    TextConsole.insert(tk.INSERT, "----------------------------------\n")
    TextConsole.see(tk.END)

# ------------------------------------------

# Créer l'app
TextureApp = tk.Tk()
TextureApp.title("Converter : Terrain")
IconPath = os.path.abspath("assets/iconterrain.ico")
TextureApp.iconbitmap(IconPath)
TextureApp.geometry("380x280")
TextureApp.resizable(False, False)

# ------------------------------------------

# Load images
youtubeImagePath = os.path.abspath("assets/youtube.png")
YoutubeImage = Image.open(youtubeImagePath)
YoutubeImageSize = YoutubeImage.resize((23, 20), Image.LANCZOS)
YoutubePhotoImage = ImageTk.PhotoImage(YoutubeImageSize)

discordImagePath = os.path.abspath("assets/discord.png")
DiscordImage = Image.open(discordImagePath)
DiscordImageSize = DiscordImage.resize((23, 20), Image.LANCZOS)
DiscordPhotoImage = ImageTk.PhotoImage(DiscordImageSize)

githubImagePath = os.path.abspath("assets/github.png")
GitHubImage = Image.open(githubImagePath)
GitHubImageSize = GitHubImage.resize((23, 20), Image.LANCZOS)
GitHubPhotoImage = ImageTk.PhotoImage(GitHubImageSize)

# Load Font 
FontMojangles = os.path.abspath("assets/Mojangles.ttf")

# ------------------------------------------

#   **--Background--**

# Global Background
Background = tk.Label(TextureApp, bg="#383838")
Background.place(x=0, y=0, width=380, height=400)

# Title Border Background
BorderBackgroundTitleApp = tk.Label(TextureApp, bg="#000000")
BorderBackgroundTitleApp.place(x=0, y=38, width=380, height=2)
BorderBackgroundTitleApp.lift()

# Background Youtube Discord
BackgroundYoutubeDiscord = tk.Label(TextureApp, bg="#585858")
BackgroundYoutubeDiscord.place(x=0, y=250, width=380, height=30)
BackgroundYoutubeDiscord.lift()
BorderBackgroundYoutubeDiscord = tk.Label(TextureApp, bg="#000000")
BorderBackgroundYoutubeDiscord.place(x=0, y=419, width=380, height=2)
BorderBackgroundYoutubeDiscord.lift()

# ------------------------------------------

#   **--Bouton--**

# Créer le bouton pour choisir la conversion
convert_button = tk.Button(TextureApp, text="Convert Blocks", command=process_images)
convert_button.place(x=100, y=62)
convert_button.configure(relief="solid", bd=2)

# Définir les options pour le menu déroulant (x16 et x32)
options = ["x16", "x32"]

# Déclarez x_multiplier comme une variable de chaîne
x_multiplier = tk.StringVar()
x_multiplier.set(options[0])  # Par défaut, x16 est sélectionné

# Créer le widget ScrolledText
TextConsole = ScrolledText(TextureApp, width=34, height=7)
TextConsole.place(x=42.5, y=113)
TextConsole.insert(tk.INSERT, "Version : 1.2 - Check if any      update have been made.\n")
TextConsole.insert(tk.INSERT, "----------------------------------\n")
TextConsole.configure(relief="solid", bd=2)

dropdown_menu = tk.OptionMenu(TextureApp, x_multiplier, *options)
dropdown_menu.place(x=200, y=59)
dropdown_menu.configure(relief="solid", bd=2)

# Action de clic pour le bouton x16
def x16_button_click():
    x_multiplier.set(1)
    convert_button.config(text="Convert Blocks (x16)")

# Action de clic pour le bouton x32
def x32_button_click():
    x_multiplier.set(2)
    convert_button.config(text="Convert Blocks (x32)")


# ------------------------------------------

#   **--Title and Background--** 

TitleAppText = "Blocks Pack Converter"
TitleAppFontSize = 25
TitleAppFont = ImageFont.truetype(FontMojangles, TitleAppFontSize)

# Image and Border
TitleAppImageWidth = 390
TitleAppImageHeight = 35
TitleAppImage = Image.new("RGBA", (TitleAppImageWidth, TitleAppImageHeight), (255, 255, 255, 0))
TitleAppDraw = ImageDraw.Draw(TitleAppImage)
TitleAppOutlineColor = (0, 0, 0)
TitleAppOutlinePosition = (37.5, 4)
TitleAppDraw.text(TitleAppOutlinePosition, TitleAppText, font=TitleAppFont, fill=TitleAppOutlineColor)

# Draw Text
TitleAppTextColor = (255, 255, 255)
TitleAppTextPosition = (36, 2)
TitleAppDraw.text(TitleAppTextPosition, TitleAppText, font=TitleAppFont, fill=TitleAppTextColor)

# Convert Image to tk
TitleAppImagetk = ImageTk.PhotoImage(TitleAppImage)

# Show Image
TitleApp = tk.Label(TextureApp, image=TitleAppImagetk, bg="#585858")
TitleApp.place(x=0, y=0)

# ------------------------------------------

#    **--YouTube Button--**

# Image
YoutubeIMG = tk.Label(TextureApp, image=YoutubePhotoImage, bg="#585858", bd=1, relief="solid")
YoutubeIMG.place(x=213, y=TextureApp.winfo_height() - 3, anchor="sw")

# Text
YoutubeText = tk.Label(TextureApp, text="Jerem2206", bg="#585858", fg="#FFFFFF")
YoutubeText.place(x=200, y=TextureApp.winfo_height() - 25, anchor="sw")
YoutubeText.place_forget()

# Display text
def YoutubeShowText(event):
    YoutubeText.place(x=200, y=TextureApp.winfo_height() - 25, anchor="sw")

# Hide text
def YoutubeHideText(event):
    YoutubeText.place_forget()

# Link
def YoutubeLink(event):
    webbrowser.open("https://www.youtube.com/channel/UC004A2sK0Pr0dD6MJzy6cTQ")

# Bind events
YoutubeIMG.bind("<Enter>", YoutubeShowText)
YoutubeIMG.bind("<Leave>", YoutubeHideText)
YoutubeIMG.bind("<Button-1>", YoutubeLink)


# ------------------------------------------

#   **--Discord Button--**

# Image
DiscordIMG = tk.Label(TextureApp, image=DiscordPhotoImage, bg="#585858", bd=1, relief="solid")
DiscordIMG.place(x=130, y=TextureApp.winfo_height() - 3, anchor="sw")

# Text
DiscordText = tk.Label(TextureApp, text="jeremestici", bg="#585858", fg="#FFFFFF")
DiscordText.place(x=113, y=TextureApp.winfo_height() - 25, anchor="sw")
DiscordText.place_forget()

# Display text
def DiscordShowText(event):
    DiscordText.place(x=113, y=TextureApp.winfo_height() - 25, anchor="sw")

# Hide text
def DiscordHideText(event):
    DiscordText.place_forget()

# Bind events
DiscordIMG.bind("<Enter>", DiscordShowText)
DiscordIMG.bind("<Leave>", DiscordHideText)


# ------------------------------------------

#    **--GitHub Button--**

# Image
GitHubIMG = tk.Label(TextureApp, image=GitHubPhotoImage, bg="#585858", bd=1, relief="solid")
GitHubIMG.place(x=171, y=TextureApp.winfo_height() - 3, anchor="sw")

# Text
GitHubText = tk.Label(TextureApp, text="jeremy2206", bg="#585858", fg="#FFFFFF")
GitHubText.place(x=151, y=TextureApp.winfo_height() - 25, anchor="sw")
GitHubText.place_forget()

# Display text
def GitHubShowText(event):
    GitHubText.place(x=151, y=TextureApp.winfo_height() - 25, anchor="sw")

# Hide text
def GitHubHideText(event):
    GitHubText.place_forget()

# Link
def GitHubLink(event):
    webbrowser.open("https://github.com/jeremy2206")

# Bind events
GitHubIMG.bind("<Enter>", GitHubShowText)
GitHubIMG.bind("<Leave>", GitHubHideText)
GitHubIMG.bind("<Button-1>", GitHubLink)

TextureApp.mainloop()
